name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: naveego/dataflow-contracts
        ref: refs/heads/master
        path: dataflow-contracts
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100 
        
    - name: Install Protoc
      uses: Arduino/actions/setup-protoc@master
    
    - name: Generate Publisher from ProtoBuf
      run: |
        cp ../dataflow-contracts/plugins/publisher.proto ./
        echo 'option csharp_namespace = "Naveego.Plugin.Sdk";' >> publisher.proto
        protoc -I=./ --csharp_out=src --csharp_opt=file_extension=.g.cs publisher.proto 

    - name: Build with dotnet
      working-directory: src
      run: dotnet build --configuration Release
