name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: naveego/dataflow-contracts
        ref: refs/heads/master
        path: dataflow-contracts
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        
    - name: Generate Publisher from ProtoBuf
      run: |
        cp ../dataflow-contracts/plugins/publisher.proto ./
        
    - name: Build with dotnet
      run: ./build.sh
                
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: library
        path: bin
      
  publish:
    runs-on: ubuntu-20.04
    needs: build
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: library
        path: bin

    - name: Push Generated Package
      working-directory: bin
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
  
          
      
    
