name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: naveego/dataflow-contracts
        ref: refs/heads/master
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100 
        
    - name: Install Protoc
      uses: Arduino/actions/setup-protoc@master
      
    - name: Build with dotnet
      working-directory: src
      run: dotnet build --configuration Release
